<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2021-12-14T14:59:34" tests="0" file="cypress/integration/recipe.feature" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Recipe" timestamp="2021-12-14T14:59:34" tests="1" time="0.0000" failures="1">
    <testcase name="Recipe I can see the Recipe" time="0.0000" classname="I can see the Recipe">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; Objects are not valid as a React child (found: object with keys {data, status, statusText, headers, config, request}). If you meant to render a collection of children, use an array instead.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application" type="Error"><![CDATA[Error: The following error originated from your application code, not from Cypress.

  > Objects are not valid as a React child (found: object with keys {data, status, statusText, headers, config, request}). If you meant to render a collection of children, use an array instead.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
    at throwOnInvalidObjectType (http://localhost:3000/static/js/vendors\x7emain.chunk.js:17492:19)
    at reconcileChildFibers (http://localhost:3000/static/js/vendors~main.chunk.js:18376:11)
    at reconcileChildren (http://localhost:3000/static/js/vendors~main.chunk.js:21196:32)
    at updateHostComponent (http://localhost:3000/static/js/vendors~main.chunk.js:21812:7)
    at beginWork (http://localhost:3000/static/js/vendors~main.chunk.js:23211:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/vendors~main.chunk.js:8169:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/vendors~main.chunk.js:8218:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/vendors~main.chunk.js:8278:35)
    at beginWork$1 (http://localhost:3000/static/js/vendors~main.chunk.js:28020:11)
    at performUnitOfWork (http://localhost:3000/static/js/vendors~main.chunk.js:26856:16)
    at workLoopSync (http://localhost:3000/static/js/vendors~main.chunk.js:26793:9)
    at renderRootSync (http://localhost:3000/static/js/vendors~main.chunk.js:26759:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/vendors~main.chunk.js:26376:22)
    at http://localhost:3000/static/js/vendors~main.chunk.js:15629:30
    at unstable_runWithPriority (http://localhost:3000/static/js/vendors~main.chunk.js:37705:16)
    at runWithPriority$1 (http://localhost:3000/static/js/vendors~main.chunk.js:15575:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/vendors~main.chunk.js:15624:13)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/vendors~main.chunk.js:15612:7)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/vendors~main.chunk.js:25976:13)
    at dispatchAction (http://localhost:3000/static/js/vendors~main.chunk.js:20345:9)
    at fetchData (http://localhost:3000/static/js/main.chunk.js:297:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>